public without sharing class fsl_Constants {
    
    /******************************
     * Accounting Job
     ******************************/

    @testVisible
    static final String ACCOUNTING_JOB_MODE_ALL = 'All';
    @testVisible
    static final String ACCOUNTING_JOB_MODE_RECORDS = 'Records';
    @testVisible
    static final String ACCOUNTING_JOB_MODE_DATES = 'Dates';

    /******************************
     * Statuses
     ******************************/

    @testVisible 
    static final String AP_STATUS_CLOSED = 'Closed';
    @testVisible 
    static final String JE_STATUS_POSTED = 'Posted';
    @testVisible 
    static final String JE_STATUS_DENIED = 'Denied';

}
